# rocky-pkg-pnetcdf
FROM rocky-pkg-builder

USER root

# Install PNetCDF build dependencies
# RUN sudo dnf install -y epel-release
RUN dnf install -y gcc-c++ openmpi-devel m4 && \
    dnf clean all

USER builder

# Set up OpenMPI environment
ENV MPI_HOME=/usr/lib64/openmpi
ENV PATH=$MPI_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH

WORKDIR /home/builder

# Assume that artifacts are going to be mounted in ~/artifacts/
RUN ln -s artifacts/Makefile .

CMD ["/bin/bash"]
